global:
  identity:
    auth:
      # Disable the Identity authentication for local development
      # it will fall back to basic-auth: demo/demo as default user
      enabled: false

# Disable identity as part of the Camunda core
identity:
  enabled: false

# Disable keycloak
identityKeycloak:
  enabled: false

console:
  ingress:
    enabled: true
    host: "console.coffee-trader.test"

operate:
  ingress:
    enabled: true
    host: "operate.coffee-trader.test"

optimize:
  enabled: false

tasklist:
  ingress:
    enabled: true
    host: "tasklist.coffee-trader.test"

# Reduce for Zeebe and Gateway the configured replicas and with that the required resources
# to get it running locally
zeebe:
  clusterSize: 1
  partitionCount: 1
  replicationFactor: 1
  pvcSize: 10Gi

zeebeGateway:
  replicas: 1
  ingress:
    rest:
      enabled: true
      host: "zeebe.coffee-trader.test"
    grpc:
      enabled: true
      host: "zeebe-grpc.coffee-trader.test"

connectors:
  enabled: true
  inbound:
    mode: disabled

elasticsearch:
  master:
    replicaCount: 1
    # Request smaller persistent volumes.
    persistence:
      size: 15Gi
